
import ProgramCodes.Classroom;
import ProgramCodes.Faculty;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author James
 */
public class MainTablePandC extends javax.swing.JFrame {

    Faculty teacher;
    Classroom c;
    /**
     * Creates new form Splash
     */
    public MainTablePandC() {
        initComponents();
    }

    public MainTablePandC(Faculty emp, Classroom c) {
        initComponents();
        teacher = emp;
        lUserName.setText(teacher.getFirstName()+ " " + teacher.getLastName());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GradesScrollPane = new javax.swing.JScrollPane();
        Grades = new javax.swing.JTable();
        btnComponents = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        btnBack = new javax.swing.JLabel();
        lbSxnSubj = new javax.swing.JLabel();
        PHSLogo = new javax.swing.JLabel();
        settingsIcon = new javax.swing.JLabel();
        lUserName = new javax.swing.JLabel();
        ribbon = new javax.swing.JLabel();
        redbar = new javax.swing.JLabel();
        bgElement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Philadelphia High School");
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Grades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Quiz", "Seatwork", "Final Rating"
            }
        ));
        GradesScrollPane.setViewportView(Grades);

        getContentPane().add(GradesScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 1080, 410));

        btnComponents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warning.png"))); // NOI18N
        btnComponents.setText("Report");
        getContentPane().add(btnComponents, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 40));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        btnSubmit.setText("Finalize");
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 500, 210, -1));

        bSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        bSave.setText("Save a copy");
        getContentPane().add(bSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        lbSxnSubj.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        lbSxnSubj.setForeground(new java.awt.Color(255, 204, 255));
        lbSxnSubj.setText("Grade & Section - Subject");
        getContentPane().add(lbSxnSubj, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 540, -1));

        PHSLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phila-logo.png"))); // NOI18N
        getContentPane().add(PHSLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));
        getContentPane().add(settingsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        lUserName.setText("User name");
        getContentPane().add(lUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        ribbon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ribbon.png"))); // NOI18N
        getContentPane().add(ribbon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        redbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bar.png"))); // NOI18N
        getContentPane().add(redbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 180, -1));

        bgElement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background2_1.png"))); // NOI18N
        getContentPane().add(bgElement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1980, 1490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grades;
    private javax.swing.JScrollPane GradesScrollPane;
    private javax.swing.JLabel PHSLogo;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel bgElement;
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton btnComponents;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lUserName;
    private javax.swing.JLabel lbSxnSubj;
    private javax.swing.JLabel redbar;
    private javax.swing.JLabel ribbon;
    private javax.swing.JLabel settingsIcon;
    // End of variables declaration//GEN-END:variables
}
