
import ProgramCodes.Employee;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author James
 */
public class UIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form UIPrincipal
     */
    public UIPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public UIPrincipal(Employee emp)
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        viewGradesPanel = new javax.swing.JPanel();
        gradeNumber = new javax.swing.JComboBox();
        Section = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        viewGradesheetsPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        panel_menu = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Philadelphia High School - Principal");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(670, 450));
        setMinimumSize(new java.awt.Dimension(670, 450));
        setPreferredSize(new java.awt.Dimension(670, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(520, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(520, 450));
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(520, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewGradesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        viewGradesPanel.setMaximumSize(new java.awt.Dimension(520, 420));
        viewGradesPanel.setMinimumSize(new java.awt.Dimension(520, 420));
        viewGradesPanel.setName("ViewGrades"); // NOI18N
        viewGradesPanel.setOpaque(false);
        viewGradesPanel.setPreferredSize(new java.awt.Dimension(520, 420));
        viewGradesPanel.setVisible(false);
        viewGradesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradeNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gradeNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeNumberActionPerformed(evt);
            }
        });
        viewGradesPanel.add(gradeNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, -1));

        Section.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewGradesPanel.add(Section, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 210, -1));

        jLabel2.setText("Grade:");
        viewGradesPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 20));

        jLabel3.setText("Section:");
        viewGradesPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 20));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Quiz1", "90", "85", "100", "-"},
                {"Quiz2", "75", "80", "90", "-"},
                {"HW1", "-", "-", "-", "80"},
                {"SW1", "100", "85", "40", "-"},
                {"PT", "85", "95", "80", "-"},
                {"Oral Participation", "95", "85", "100", ""},
                {"", null, null, null, null}
            },
            new String [] {
                "Activity", "Knowledge", "Process", "Skills", "Product/Performances"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        viewGradesPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 490, 140));

        jLabel4.setText("Averages");
        viewGradesPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, -1));

        jLabel5.setText("Knowledge:");
        viewGradesPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 20));

        jLabel6.setText("Process:");
        viewGradesPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, -1));

        jLabel7.setText("Skills:");
        viewGradesPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 160, -1));

        jLabel8.setText("Product/Perormance:");
        viewGradesPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 160, -1));

        jLabel9.setText("------------------------------------------------------------------");
        viewGradesPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jLabel10.setText("FINAL RATING:");
        viewGradesPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jLabel11.setText("<Numeric Value> & <Letter Value>");
        viewGradesPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        jLabel12.setText("<Numeric Value>");
        viewGradesPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 90, 20));

        jLabel13.setText("<Numeric Value>");
        viewGradesPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 90, 20));

        jLabel14.setText("<Numeric Value>");
        viewGradesPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 90, 20));

        jLabel15.setText("<Numeric Value>");
        viewGradesPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 90, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewGradesPanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 210, 20));

        jLabel20.setText("Subject:");
        viewGradesPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewGradesPanel.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 210, -1));

        jLabel22.setText("Name:");
        viewGradesPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewGradesPanel.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, -1));

        jLabel23.setText("Quarter:");
        viewGradesPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 50, 20));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewGradesPanel.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_panelbg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        viewGradesPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, 390));

        jPanel1.add(viewGradesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        viewGradesheetsPanel.setMaximumSize(new java.awt.Dimension(500, 450));
        viewGradesheetsPanel.setMinimumSize(new java.awt.Dimension(500, 450));
        viewGradesheetsPanel.setOpaque(false);
        viewGradesheetsPanel.setPreferredSize(new java.awt.Dimension(520, 450));
        viewGradesheetsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        viewGradesheetsPanel.setVisible(false);

        jLabel16.setText("Grade:");
        viewGradesheetsPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewGradesheetsPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, -1));

        jLabel17.setText("Section:");
        viewGradesheetsPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 50, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Filipino", "English", "Mathematics", "Science", "Social Studies", "Christian Living", "THE", "MAPEH", "Co-Curricular", "Conduct"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        viewGradesheetsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 490, 270));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewGradesheetsPanel.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 210, -1));

        jLabel21.setText("Subject:");
        viewGradesheetsPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 50, 20));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewGradesheetsPanel.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 210, -1));

        jLabel24.setText("Quarter:");
        viewGradesheetsPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 50, 20));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        viewGradesheetsPanel.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_panelbg.png"))); // NOI18N
        jLabel18.setText("jLabel1");
        viewGradesheetsPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, -1));

        jPanel1.add(viewGradesheetsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 380));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("View Gradesheets");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, -1));

        jButton3.setText("Return Grades");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, -1));

        jButton1.setText("View Grades");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, -1));

        jButton4.setText("Notifications");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, -1));

        jButton7.setText("Logout");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 110, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phila-logo.png"))); // NOI18N
        logo.setText("jLabel20");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        panel_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel_menu.png"))); // NOI18N
        panel_menu.setText("jLabel19");
        panel_menu.setPreferredSize(new java.awt.Dimension(130, 430));
        getContentPane().add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 430));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        background.setText("jLabel21");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_panelbg.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 530, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gradeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeNumberActionPerformed
        // TODO add your handling code here:
        SectionDAO a = new SectionDAO();
        ArrayList<String> sList = new ArrayList();
        sList = a.getSectionList((String) gradeNumber.getSelectedItem());
        Section.setModel(new javax.swing.DefaultComboBoxModel(sList.toArray()));
       SectionActionPerformed(evt);
    }//GEN-LAST:event_gradeNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  SectionDAO a = new SectionDAO();
       ArrayList<String> gList = new ArrayList();
       gList = a.getYearList();
       gradeNumber.setModel(new javax.swing.DefaultComboBoxModel(gList.toArray()));
        gradeNumberActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        viewGradesPanel.setVisible(true);
        viewGradesheetsPanel.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        viewGradesheetsPanel.setVisible(true);
        viewGradesPanel.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void SectionActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        subjectDAO a = new subjectDAO();
        ArrayList<String> List = new ArrayList();
        List = a.getSubjectNames((String) Section.getSelectedItem(),(String) gradeNumber.getSelectedItem());
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(List.toArray()));
        jComboBox3ActionPerformed(evt);
    }                                       

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        StudentDAO a = new StudentDAO();
        ArrayList<String> List = new ArrayList();
        List = a.getStudentListP((String) Section.getSelectedItem());
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(List.toArray()));
        jComboBox6ActionPerformed(evt);
    }                                          

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
         StudentDAO a = new StudentDAO();
         System.out.println("StudentID: "+ a.getStudentID((String)jComboBox6.getSelectedItem()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Section;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox gradeNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel panel_menu;
    private javax.swing.JPanel viewGradesPanel;
    private javax.swing.JPanel viewGradesheetsPanel;
    // End of variables declaration//GEN-END:variables
}
